baseline_oct25.o: baseline_oct25.cpp ../binary_files/binary_files.cpp ../binary_files/binary_files.h
	g++ -lgsl -lgslcblas -lm -c baseline_oct25.cpp -o baseline_oct25.o

clean:
	rm *.o baseline_executable
