svd_oct25.o: svd_oct25.cpp ../binary_files/binary_files.cpp ../binary_files/binary_files.h ../Baseline_Oct25/baseline_oct25.o
	g++ -lgsl -lgslcblas -lm -c svd_oct25.cpp -o svd_oct25.o

clean:
	rm *.o svd_executable
